[package]
name = "lamb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dialoguer = { version = "0.11.0", features = ["history"] }
env_logger = "0.11.5"
nom = "7.1.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.24.0"
